# Generated by Django 4.2.7 on 2026-06-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('UZS', 'UZS'), ('RUB', 'RUB')], default='USD', max_length=3, verbose_name='Валюта')),
                ('category', models.CharField(choices=[('food', 'Еда'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения'), ('health', 'Здоровье'), ('shopping', 'Покупки'), ('utilities', 'Коммунальные'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('voice_transcript', models.TextField(blank=True, verbose_name='Транскрипция голоса')),
                ('expense_date', models.DateField(verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
